### ISSUE TITLE
Architecture refine

### ISSUE THREAD

**Issue by MiguelMachado-dev** [forjadev/gun-organization#7]
![Image](https://user-images.githubusercontent.com/29252011/255301029-a11eb3b4-f3a6-4982-ade1-c33857acba7c.png)

**Comment by jbiers** [comment]
Let's define a time on Tuesday (July 25th) for us to meet and define an architectural drawing together. My personal suggestion would be 19:30. What do you guys think?

Also, later tonight I will post here some docs and useful links that should make some topics a bit clearer to those of you who are still a little confused about how each piece of this puzzle works :))

**Comment by tiburciohugo** [comment]
Works for me, I'll be waiting for the docs thing. Appreciated!

**Comment by pedrovianadev** [comment]
19:30 it's good for me!

**Comment by jbiers** [comment]
As promised, I am leaving here a list of concepts and questions to guide your learning so that everyone is better prepared to understand our architecture. Also, I'll link some resources to be read but I encourage you to supplement this with your own research. As a prerequisite knowledge, I suggest you have some understanding of the HTTP protocol and its main methods.

**Webhooks**
- what is a webhook?
- understand the structure of a webhook sent by github. what data do you receive from it?
- how can our server be sure the webhook actually came from github?
- is there a default HTTP method github uses in its webhooks?
_https://docs.github.com/en/webhooks-and-events/webhooks/about-webhooks_
_https://www.youtube.com/watch?v=mrkQ5iLb4DM&ab_channel=codedamn_

**API**
- what is an API?
- what are the advantages of building our own API? why not consume the data straight from Github?
- be able to describe the roles of a client and a server.
_https://www.hostinger.com.br/tutoriais/api-restful_
_https://www.youtube.com/watch?v=9SbUPqKEWcY&ab_channel=MatheusBattisti-HoradeCodar_

**Github Actions and CI/CD**
- what is CI/CD? what are the main tools used for it besides Github Actions?
- understand what are workflows and jobs.
- what can trigger a workflow? is it possible to trigger a workflow via an HTTP request? if so, how?
- what are events in Github?
_https://docs.github.com/en/webhooks-and-events/events/github-event-types_
_https://docs.github.com/en/actions/learn-github-actions_
_https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner_
_https://about.gitlab.com/topics/ci-cd/_

**Comment by MVPC92** [comment]
19:30 is ok

**Comment by vinirossado** [comment]
If every time a user is added to GitHub, it triggers a Webhook and then an ApiRest for updates, what purpose does a CRON serve? The trigger will always originate from GitHub, right?

**Comment by MarkimQ** [comment]
19:30 is ok for me

**Comment by junio256** [comment]
> If every time a user is added to GitHub, it triggers a Webhook and then an ApiRest for updates, what purpose does a CRON serve? The trigger will always originate from GitHub, right?

Agree, seems redundant

**Comment by jbiers** [comment]
The cronjob is supposed to update all user data, as it's possible to change your github username and email and those do not generate events for the org. This was the solution we came up with, if you guys have any other suggestions feel free to comment below.

**Comment by junio256** [comment]
Maybe we could use hash functions to compare old and current data, in case it didn't match it would update everything

**Comment by MiguelMachado-dev** [comment]
the idea of being redundant is what we described on our last meeting. It's to build a complete service that everyone can learn all steps, building CRON, REST API and also Webhook. As @jbiers said, if someone changes their profile picture or handle, it will not trigger an event and it will be outdated, so we thought of creating a CRON to fetch all latest data to save on our database!

This will be the architecture we are going to follow unless you guys have any other idea on how this should happen so we can update that mental flow so people on this issue can work with latest decisions

**Comment by vinirossado** [comment]
> The cronjob is supposed to update all user data, as it's possible to change your github username and email and those do not generate events for the org. This was the solution we came up with, if you guys have any other suggestions feel free to comment below.

But is it necessary to have this level of "sync" I'm not sure but for me there is no point to do it since it's not often someone update basic information such as: Name

**Comment by MiguelMachado-dev** [comment]
> But is it necessary to have this level of "sync" I'm not sure but for me there is no point to do it since it's not often someone update basic information such as: Name

Not name, but people can update their photo and specially their handle. So I think this is a good feature to cover :)

**Comment by vinirossado** [comment]
> the idea of being redundant is what we described on our last meeting. It's to build a complete service that everyone can learn all steps, building CRON, REST API and also Webhook. As @jbiers said, if someone changes their profile picture or handle, it will not trigger an event and it will be outdated, so we thought of creating a CRON to fetch all latest data to save on our database!
> 
> This will be the architecture we are going to follow unless you guys have any other idea on how this should happen so we can update that mental flow so people on this issue can work with latest decisions

As a form of study, it is acceptable, but beyond that, I think it is just over-engineering to achieve an unnecessary level of synchronization.

**Comment by vinirossado** [comment]
Further to my previous answer, learning to use cron can be beneficial, especially in the context of study. However, we have to be careful that those who are learning do not go off over-engineering simple tasks.

**Comment by MiguelMachado-dev** [comment]
I do not believe that is the case, because the only moment we are actually hitting github API is on this CRON to fetch latest info of each user. Otherwise, it's just a webhook that triggers our webhook server to save user data on database and a REST API to give those data when hit.

**Comment by vinirossado** [comment]
> I do not believe that is the case, because the only moment we are actually hitting github API is on this CRON to fetch latest info of each user. Otherwise, it's just a webhook that triggers our webhook server to save user data on database and a REST API to give those data when hit.

Webhooks can trigger any action, making it possible for GitHub to call our API and save data into the database while also updating GitHub-related items. However, is it necessary to engage in over-engineering to synchronize photos? Considering that the name will not change often,

**Comment by MiguelMachado-dev** [comment]
But you are focusing only in the name, people can change their photo or handle any time, specially those who are just starting and created their account only to participate on Pro!

**Comment by MiguelMachado-dev** [comment]
Also, github org webhook does not trigger on member account changes, only for member update (delete, member added and so on)

**Comment by jbiers** [comment]
Architecture defined during meeting. Any questions or feedback are welcome.

[lucidchart link - log in to view](https://lucid.app/lucidchart/301badf9-ff04-4a07-98ce-07e92adc0af7/edit?viewport_loc=239%2C-91%2C1943%2C1116%2C0_0&invitationId=inv_3c8c948d-78ff-4d00-8f93-c7595e85fe81)


![Image](https://github.com/forjadev/gun-organization/assets/85142222/233d0a19-fc77-4026-a792-8a3d0fecb1aa)
